### PR TITLE
Implement heartbeat

### PR DESCRIPTION
**Pull request by akloboucnik**
My take on #95.

I based the impementation on https://docs.google.com/presentation/d/1Hlv4qaWm2PRU04dVPmShP9wU7TEQEttXdsbV8P54Uvw/edit#slide=id.ge4c0ef0fc0_0_2 and https://www.rabbitmq.com/heartbeats.html#heartbeats-interval

### TODO

- [x] disabling heartbeat (https://www.rabbitmq.com/heartbeats.html#disabling)
- [ ] test

### CODE REVIEW

**Comment by michaelklishin** [comment]
@akloboucnik from our experience with heartbeat implementations in other clients (not just RabbitMQ Stream Protocol ones), it is notoriously difficult to integration test. I'd be happy to test this PR, perhaps do a bit of renaming and try to get it over the line.

Would that be OK with you?

**Comment by wolf4ood** [comment]
@michaelklishin 

this was stalled and basically the worked has been finished here

https://github.com/rabbitmq/rabbitmq-stream-rust-client/pull/163

Let in case let me know if you have time to test it :)

**Comment by michaelklishin** [comment]
@wolf4ood ah, I see. So this should be closed then.

**Comment by Gsantomaggio** [comment]
@wolf4ood we can close this, right?

**Comment by akloboucnik** [comment]
@michaelklishin Sorry, I had to move on working on more pressing things at work and never got back to this :-(

@wolf4ood Thank you for implementing this!

**Pull request closed without merging**
